export const LOAD_PRODUCTS_SUCCESS = "LOAD_PRODUCTS_SUCCESS";
export const SEARCH_PRODUCTS_SUCCESS = "SEARCH_PRODUCTS_SUCCESS";
export const SORT_PRODUCTS_SUCCESS = "SORT_PRODUCTS_SUCCESS";
export const TOTAL_RESULT_COUNT = "TOTAL_RESULT_COUNT";
